version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: project_3a_image
    container_name: project-3a-container
    ports:
      - "5003:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
